FROM ubuntu:24.04

# Install required packages
RUN DEBIAN_FRONTEND=noninteractive \ 
    apt-get update \
    && apt-get install -y wget bzip2 xz-utils make cmake sudo \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Create a non-root user named logger
RUN groupadd logger && useradd -rm -d /home/logger -s /bin/bash -g logger -G sudo -u 1001 logger

# Switch to non-root user
USER logger
WORKDIR /home/logger
