on: [push]
jobs:
  build_static_analysis_and_unit_tests:
    runs-on: ubuntu-latest
    container: 
      image: rbarresi10/genlogger_arm_gcc_13.2

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Create build directory
        run: mkdir -p build
      
      - name: Check directory (before entering)
        run: pwd

      - name: Configure CMake
        run: cmake .. -Dtarget_type=host
        working-directory: build

      - name: Check directory (inside build)
        run: pwd
        working-directory: build
