on: [push]
jobs:
  build_static_analysis_and_unit_tests:
    runs-on: ubuntu-latest
    container: 
      image: rbarresi10/genlogger_arm_gcc_13.2

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Create build directory
        run: mkdir -p build

      - name: Configure CMake
        run: cmake .. -Dtarget_type=host
        working-directory: build

      - name: Build project
        run: make -j$(nproc)
        working-directory: build

      - name: Run unit tests
        run: ./testFilesystem
        working-directory: build/test/src

      - name: Check test results
        run: |
          if ./testFilesystem | grep -q "FAIL"; then
            echo "Tests failed!"
            exit 1
          else
            echo "All tests passed!"
          fi
        working-directory: build/test/src
