on: [push]
jobs:
  build_static_analysis_and_unit_tests:
    runs-on: ubuntu-latest
    container: 
      image: rbarresi10/genlogger_arm_gcc_13.2

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Create build_host directory
        run: mkdir -p build_host

      - name: Create build_target directory
        run: mkdir -p build_target

      - name: Configure CMake (target)
        run: cmake .. -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/cross/stm32f429.cmake -DCMAKE_BUILD_TYPE=Debug -Dtarget_type=target
        working-directory: build_target

      - name: Build project (target)
        run: make -j$(nproc)
        working-directory: build_target

      - name: Configure CMake (host)
        run: cmake .. -Dtarget_type=host
        working-directory: build_host

      - name: Build project
        run: make -j$(nproc)
        working-directory: build_host

      - name: Run unit tests
        run: ./generalTests
        working-directory: build_host/test/src

      - name: Check test results
        run: |
          if ./generalTests | grep -q "FAIL"; then
            echo "Tests failed!"
            exit 1
          else
            echo "All tests passed!"
          fi
        working-directory: build/test/src
