on: [push]
jobs:
  build_static_analysis_and_unit_tests:
  runs-on: ubuntu-latest
  container: 
	image: rbarresi10/genlogger_arm_gcc_13.2
  steps:
	- name: checkout the repository
	uses: actions/checkout@v3
	- run: cmake .. -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/cross/stm32f429.cmake -DCMAKE_BUILD_TYPE=Debug -Dtarget_type=target