name: AI Code Review

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  ai-review:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: AI PR Review
        uses: villesau/ai-code-review-action@v2
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          model_name: gpt-4o-mini
          model_temperature: 0
          exclude_files: '*.md,*.json,*.yml'